# Generated by Django 3.0.5 on 2020-04-07 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=30)),
                ('client_type', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='PerformanceData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_system_voltage', models.DecimalField(decimal_places=6, max_digits=6)),
                ('voc', models.DecimalField(decimal_places=6, max_digits=6)),
                ('isc', models.DecimalField(decimal_places=6, max_digits=6)),
                ('vmp', models.DecimalField(decimal_places=6, max_digits=6)),
                ('imp', models.DecimalField(decimal_places=6, max_digits=6)),
                ('pmp', models.DecimalField(decimal_places=6, max_digits=6)),
                ('ff', models.DecimalField(decimal_places=6, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=30)),
                ('cell_technology', models.CharField(max_length=30)),
                ('cell_manufacturer', models.CharField(max_length=30)),
                ('number_of_cells', models.PositiveIntegerField()),
                ('number_of_cells_in_series', models.PositiveIntegerField()),
                ('number_of_series_strings', models.PositiveIntegerField()),
                ('number_of_diodes', models.PositiveIntegerField()),
                ('product_length', models.DecimalField(decimal_places=6, max_digits=6)),
                ('product_width', models.DecimalField(decimal_places=6, max_digits=6)),
                ('product_weight', models.DecimalField(decimal_places=6, max_digits=6)),
                ('superstrate_type', models.CharField(max_length=30)),
                ('superstrate_manufacturer', models.CharField(max_length=30)),
                ('substrate_type', models.CharField(max_length=30)),
                ('substrate_manufacturer', models.CharField(max_length=30)),
                ('frame_type', models.CharField(max_length=30)),
                ('frame_adhesive', models.CharField(max_length=30)),
                ('encapsulate_type', models.CharField(max_length=30)),
                ('encapsulant_manufacturer', models.CharField(max_length=30)),
                ('junction_box_type', models.CharField(max_length=30)),
                ('junction_box_manufacturer', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TestSequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TestStandard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard_name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('published_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('middle_name', models.CharField(max_length=30)),
                ('job_title', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('office_phone', models.CharField(max_length=14)),
                ('cell_phone', models.CharField(max_length=14)),
                ('prefix', models.CharField(max_length=30)),
                ('client_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('is_fi_required', models.BooleanField()),
                ('fi_frequency', models.DecimalField(decimal_places=6, max_digits=6)),
                ('standard_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.TestStandard')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address1', models.CharField(max_length=30)),
                ('address2', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('postal_code', models.CharField(max_length=5)),
                ('country', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=14)),
                ('fax_number', models.CharField(max_length=14)),
                ('client_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_number', models.CharField(max_length=30)),
                ('issue_date', models.DateField()),
                ('location_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Location')),
                ('model_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Product')),
                ('standard_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.TestStandard')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.User')),
            ],
        ),
    ]
