# Generated by Django 3.0.5 on 2020-04-07 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PerformanceData',
        ),
    ]
