# Generated by Django 3.0.5 on 2020-04-07 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_delete_performancedata'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_system_voltage', models.DecimalField(decimal_places=6, max_digits=6)),
                ('voc', models.DecimalField(decimal_places=6, max_digits=6)),
                ('isc', models.DecimalField(decimal_places=6, max_digits=6)),
                ('vmp', models.DecimalField(decimal_places=6, max_digits=6)),
                ('imp', models.DecimalField(decimal_places=6, max_digits=6)),
                ('pmp', models.DecimalField(decimal_places=6, max_digits=6)),
                ('ff', models.DecimalField(decimal_places=6, max_digits=6)),
                ('model_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Product')),
                ('sequence_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.TestSequence')),
            ],
        ),
    ]
